# Arrays Numpy: criação, indexação e manipulação

In [1]:
import numpy as np

In [ ]:
# Criando um array 1D
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1D:", arr1)

Array 1D: [1 2 3 4 5]


In [ ]:
# Criando um array 2D (matriz)
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("\nArray 2D (matriz):")
print(arr2)


Array 2D (matriz):
[[1 2 3]
 [4 5 6]]


In [ ]:
# Criando array com zeros
zeros_arr = np.zeros(5)
print("\nArray de zeros:", zeros_arr)


Array de zeros: [0. 0. 0. 0. 0.]


In [ ]:
# Criando array com uns
ones_arr = np.ones((2, 3))
print("\nArray de uns:")
print(ones_arr)


Array de uns:
[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# Método Matrix - String

a = np.matrix('1 2; 3 4')
print(a)

[[1 2]
 [3 4]]


In [19]:
# Método Matrix - List/array
b = np.matrix([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
# Indexação em array 1D
arr = np.array([10, 20, 30, 40, 50])
print("Array original:", arr)
print("Primeiro elemento:", arr[0])
print("Último elemento:", arr[-1])
print("Elementos do índice 1 ao 3:", arr[1:4])

Array original: [10 20 30 40 50]
Primeiro elemento: 10
Último elemento: 50
Elementos do índice 1 ao 3: [20 30 40]


In [ ]:
# Indexação em array 2D
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nMatriz original:")
print(matriz)
print("\nElemento na linha 1, coluna 2:", matriz[1,2])
print("Segunda linha completa:", matriz[1])
print("Primeira coluna:", matriz[:,0])


Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elemento na linha 1, coluna 2: 6
Segunda linha completa: [4 5 6]
Primeira coluna: [1 4 7]


In [ ]:
# Indexação booleana
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("\nArray original:", arr)
print("Elementos maiores que 5:", arr[arr > 5])
print("Elementos pares:", arr[arr % 2 == 0])


Array original: [1 2 3 4 5 6 7 8 9]
Elementos maiores que 5: [6 7 8 9]
Elementos pares: [2 4 6 8]


In [ ]:
# Manipulação de Arrays

# Criando um array exemplo
arr = np.array([1, 2, 3, 4, 5])
print("Array original:", arr)

Array original: [1 2 3 4 5]


## Operações matemáticas com Numpy

In [ ]:
# Operações aritméticas com arrays
print("\nArray + 2:", arr + 2)
print("Array * 3:", arr * 3)
print("Array ao quadrado:", arr ** 2)


Array + 2: [3 4 5 6 7]
Array * 3: [ 3  6  9 12 15]
Array ao quadrado: [ 1  4  9 16 25]


In [ ]:
# Funções matemáticas
print("\nRaiz quadrada:", np.sqrt(arr))
print("Exponencial:", np.exp(arr))
print("Seno:", np.sin(arr))


Raiz quadrada: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Seno: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


## Estatísticas básicas com Numpy

In [ ]:
# Estatísticas básicas
print("\nMédia:", np.mean(arr))
print("Desvio padrão:", np.std(arr))
print("Valor máximo:", np.max(arr))
print("Valor mínimo:", np.min(arr))


Média: 3.0
Desvio padrão: 1.4142135623730951
Valor máximo: 5
Valor mínimo: 1


## Outras manipulações

In [ ]:
# Transposição
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\nMatriz original:")
print(matriz)
print("\nMatriz transposta:")
print(matriz.T)


Matriz original:
[[1 2 3]
 [4 5 6]]

Matriz transposta:
[[1 4]
 [2 5]
 [3 6]]


In [9]:
# Shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [7]:
# Reshape 1D -> 2D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Concatenação de arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("\nConcatenação horizontal:", np.hstack((arr1, arr2)))
print("Concatenação vertical:", np.vstack((arr1, arr2)))


Concatenação horizontal: [1 2 3 4 5 6]
Concatenação vertical: [[1 2 3]
 [4 5 6]]


In [2]:
# Amostras e população - Split

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [4]:
# Loop em arrays 1D

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [5]:
# Loop em arrays 2D


arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


## Filtros

In [10]:

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [11]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [12]:

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [13]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


Aqui estão algumas bibliotecas populares que são baseadas no **NumPy** e usam ele "por debaixo dos panos", oferecendo funcionalidades e abstrações mais específicas:

### 1. **Pandas**
   - **Descrição**: O Pandas é uma biblioteca poderosa para manipulação de dados. Ele usa o NumPy para suas estruturas de dados subjacentes (`Series` e `DataFrame`), proporcionando operações eficientes em grandes volumes de dados.
   - **Uso do NumPy**: Pandas usa arrays NumPy para armazenar dados em suas `Series` e `DataFrame`. Internamente, muitas operações no Pandas são baseadas em funções do NumPy.
   - **Link**: [Pandas](https://pandas.pydata.org/)

### 2. **SciPy**
   - **Descrição**: A SciPy é uma biblioteca científica que oferece muitas funções matemáticas, como álgebra linear, integração, otimização, entre outras.
   - **Uso do NumPy**: O SciPy depende fortemente do NumPy para arrays e operações numéricas eficientes, além de estender essas operações com funcionalidades adicionais.
   - **Link**: [SciPy](https://www.scipy.org/)

### 3. **Matplotlib**
   - **Descrição**: Matplotlib é uma biblioteca popular para criação de gráficos e visualizações.
   - **Uso do NumPy**: Para criar visualizações, o Matplotlib frequentemente usa arrays do NumPy para representar dados numéricos e manipular gráficos.
   - **Link**: [Matplotlib](https://matplotlib.org/)

### 4. **Scikit-learn**
   - **Descrição**: A Scikit-learn é uma das bibliotecas mais populares para aprendizado de máquina em Python, oferecendo implementações de modelos de classificação, regressão, clustering, etc.
   - **Uso do NumPy**: O Scikit-learn usa o NumPy para manipulação eficiente de arrays de dados, bem como para cálculos numéricos durante o treinamento e a predição de modelos.
   - **Link**: [Scikit-learn](https://scikit-learn.org/)

### 5. **CuPy**
   - **Descrição**: CuPy é uma biblioteca que oferece funções semelhantes ao NumPy, mas com suporte para operações em GPUs usando CUDA. Ela permite acelerar computações numéricas em dispositivos gráficos.
   - **Uso do NumPy**: A API do CuPy é muito similar à do NumPy, mas as operações são realizadas usando GPUs, utilizando o PyCUDA internamente.
   - **Link**: [CuPy](https://cupy.dev/)

### 6. **TensorFlow**
   - **Descrição**: O TensorFlow é uma das bibliotecas mais conhecidas para aprendizado profundo e redes neurais, embora também seja usado para outras tarefas de aprendizado de máquina.
   - **Uso do NumPy**: O TensorFlow usa arrays do NumPy para representar dados de entrada e saída, embora ele tenha sua própria abstração (tensores). Algumas operações podem ser realizadas diretamente usando o NumPy no TensorFlow.
   - **Link**: [TensorFlow](https://www.tensorflow.org/)

### 7. **PyTorch**
   - **Descrição**: PyTorch é outra biblioteca muito popular para aprendizado profundo, similar ao TensorFlow. Ele também oferece uma abstração de tensor para cálculos eficientes, especialmente em GPUs.
   - **Uso do NumPy**: PyTorch tem integração com o NumPy, e muitas vezes você pode converter entre tensores do PyTorch e arrays do NumPy de forma transparente.
   - **Link**: [PyTorch](https://pytorch.org/)

### 8. **SymPy**
   - **Descrição**: SymPy é uma biblioteca de álgebra computacional, permitindo computações simbólicas e simbólicas-numéricas.
   - **Uso do NumPy**: O SymPy pode usar o NumPy internamente para operações numéricas quando realiza computações simbólicas em que números reais ou complexos são envolvidos.
   - **Link**: [SymPy](https://www.sympy.org/)

### 9. **xarray**
   - **Descrição**: xarray é uma biblioteca que estende a funcionalidade do Pandas para trabalhar com dados multidimensionais (como arrays de mais de duas dimensões) de maneira eficiente.
   - **Uso do NumPy**: A estrutura de dados `DataArray` do xarray é baseada no NumPy, oferecendo operações semelhantes a arrays, mas com suporte a metadados adicionais e coordenação de eixos.
   - **Link**: [xarray](http://xarray.pydata.org/)

### 10. **Dask**
   - **Descrição**: Dask é uma biblioteca que permite computação paralela e distribuída em Python, especialmente útil para processamento de grandes volumes de dados.
   - **Uso do NumPy**: Dask usa arrays do NumPy para representar dados, mas com suporte para processamento paralelo e distribuição em clusters, o que permite lidar com dados maiores do que a memória local.
   - **Link**: [Dask](https://dask.org/)

Essas bibliotecas são algumas das mais conhecidas que utilizam o NumPy em suas implementações internas, mas muitas outras também podem depender dele, dado que o NumPy oferece uma base sólida para operações numéricas de baixo nível.