# O que é Numpy e sua importância na análise de dados

In [3]:
import numpy as np

In [4]:
# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Perform some basic operations
print("Original array:", arr) # imprime o array original
print("Array mean:", np.mean(arr)) # imprime a média do array
print("Array sum:", np.sum(arr)) # imprime a soma do array
print("Array squared:", np.square(arr)) # imprime o array elevado ao quadrado

# Create a 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("\n2D array:")
print(matrix) # imprime o array 2D - matriz
print("Matrix transpose:")
print(matrix.T) # imprime a transposta da matriz


Original array: [1 2 3 4 5]
Array mean: 3.0
Array sum: 15
Array squared: [ 1  4  9 16 25]

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
